# Generated by Django 5.2.5 on 2025-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_postsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
