version: "3.9"
services:
  redis:
    image: redis:7
  backend:
    build: ../backend
    env_file:
      - ./.env.prod
    depends_on:
      - redis
    ports: []
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - static:/app/staticfiles
      - media:/app/media
  frontend:
    build: ../frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
    env_file:
      - ./.env.prod
    depends_on:
      - backend
    ports: []
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 5
  proxy:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
volumes:
  static:
  media:

